### ISSUE TITLE
Enhanced AI properties don't apply or cause crash

### ISSUE THREAD

**Issue by Nyxteroid** [Insane-96/MobRandomness#177]
### Minecraft Version

1.20.1

### Modloader

Forge

### Are you using servers that accept plugins such as Bukkit or Paper?

No

### Modloader Version

47.4.10

### InsaneLib Version

1.23.0

### MPR Version

5.1.2.2

### Describe your issue

--- Enhaced AI property Issue ---
- It seems that this issue either prevents changes from beign applied to entites, or straight just crash the game when spawning them with a spawn egg
- I first tried applying the leader data to an entity, and when summoning them with commands they just didn't spawn at all, not even the command prompt appeared
- I tried to apply the example from the wiki to a husk too and the same happened
- Later I tested that again and found that the game crashes when trying to spawn a mob with an egg
- Lastly I tested with the miner AI on husks too, and in this case nothing happened, I checked their nbts and there was no change at all, no crash nor anything else, even if they spawned with the miner AI by the Enhanced AI mod

-- 1st JSON used to test the Enhanced AI property --
```
{
    "target": "minecraft:husk",
    "properties": [
        {
            "property": "enhancedai:change_data",
            "data": "enhancedai:leaders/leader",
            "value": 1
        }
    ]
} 
```

-- Enhanced AI property issue crash message --
The game crashed: exception in server tick loop
Error: java.lang.NoSuchMethodError: 'double insane96mcp.mobspropertiesrandomness.data.json.util.modifiable.MPRRange.getValue(net.minecraft.world.entity.LivingEntity)'

(Just in case, I tested these with others mobs too)

<img width="1920" height="1051" alt="Image" src="https://github.com/user-attachments/assets/47ed7ed3-f036-4ba6-8351-22c942550978" />
This dud just wore a spider as a hat and came to a crazy sleepover party

### Reproduce the issue with just MPR

Yes

### Performance Enchancers

None of the above

### Sinytra Connector

No

### Confirm the following

Checked pinned issues, Searched existing issues

**Comment by Insane96** [comment]
Fixed with latest Enhanced AI

**Comment by Nyxteroid** [comment]
- Would like to mention, I tried this out again with the latest release of Enhanced AI (3.3.5)
- It's nothing game breaking, but it seems there's still an issue when trying to spawn mobs with Enhanced AI properties that are booleans, like with the same example I provided above
- I tested it with the sprint and climbing data keys too
- Nothing spawns, I tried it with eggs and commands
- When trying to spawn with commands I get this message in chat, with red text:
   "An unexpected error occurred trying to execute that command"
- If i'm not making any mistakes, I should be using "0" & "1" as "false" & "true"?
- Integer values and string types work just fine (though I don't know how to add multiple entities there, I'll guess by creating a tag file?)

**Comment by Insane96** [comment]
The log should show why the mob fails to spawn

**Comment by Nyxteroid** [comment]
Right, uhh... I think it's this, what I get:

https://mclo.gs/25MJ2iL
(I should be using this page right? First times I'm sorry)

I think I can understand that this is because it doesn't accept booleans...? Hmm

**Comment by Nyxteroid** [comment]
I think I see my problem, now I don't know how to use round D:

**Comment by Insane96** [comment]
Fixed with last release
